defaults:
  - _self_ 
  - callbacks: speaker_default
  - data/module: voxceleb1
  - data/pipeline: xvector_pipeline
  - data/shards: shards_voxceleb
  - data/dataloader: speaker
  - evaluator: cosine_distance
  - network: xvector
  - tokenizer: default
  - optim/algo: adam
  - optim/schedule: constant
  - optim/loss: cross_entropy
  - trainer: trainer

  # setting a profiler changes the trainer to 1 epoch
  # in order to debug performance
  - profiler: null

# root directory with subfolders containing the canonical dataset(s)
data_folder: ${oc.env:DATA_FOLDER}

# directory for temporary storage
temp_folder: ${oc.env:TEMP_FOLDER}

# directory for slurm and hydra logs
log_folder: ${oc.env:LOG_FOLDER}

# random seed used by the experiment
seed: 42133724

# whether to tune model
tune_model: False
tune_iterations: 1000

# verify model (run e.g summary and BatchGradientVerification)
verify_model: false

# whether to fit model
fit_model: True

# whether to evaluate model
eval_model: True

# whether to load the weight of the networks from a checkpoint
load_network_from_checkpoint: null

# whether to log to comet-ml
use_cometml: ${oc.decode:${oc.env:USE_COMET_ML}}

# number of gpus to use
gpus: ${oc.decode:${oc.env:NUM_GPUS}}

# project name (useful for giving a name to log directories)
project_name: general

# experiment name
# (:) indicates it needs to be resolved
experiment_name: ${random_uuid:}

# tag to add to the experiment dashboard for easy filtering
# of certain experiment
tag: ${now:%Y-%m-%d}

# config variables for hydra
hydra:
  run:
    # set root output directory
    dir: ${log_folder}/wav2vec_speaker_identification/run/${now:%Y-%m-%d_%H-%M-%S}/${experiment_name}
  sweep:
    # set root output directory
    dir: ${log_folder}/wav2vec_speaker_identification/sweep/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${experiment_name}